### ISSUE TITLE
Test files are not linted properly 

### ISSUE THREAD

**Issue by andytango** [ianaya89/generator-babel-webpack-karma#1]
Hey, great generator -- thanks for writing it!  

One thing I've noticed is that my test files aren't linted using the ESLint mocha plugin, so it reports that describe isn't defined and various other things. This wouldn't be such a big deal except that I like the pre-commit hook and don't really want to relax ESLint's settings.

I've resolved this on my own project by adding the plugin and copying the eslint_rc.json config file, thinking that I might want to have other different style rules for test files in general. You can see the fix here:

https://github.com/andytango/yp-js/commit/8d1d658fad424105a24120976cf5aa119d0e46ef

If you think this would work for the generator's template, would you like me to submit a PR?

**Comment by ianaya89** [comment]
Hey, thanks for your feedback. I think is a good idea, I would like to see it working. Your PR is welcome!

**Comment by ianaya89** [comment]
Solved in PR #2
